image: ritproject/cli:docker
services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
stages:
  - test
  - update internal images
before_script:
  - rit config tunnel add repo https://gitlab.com/ritproject/workspace
  - rit config tunnel default set workspace

# Stage: test

test:
  stage: test
  script: rit tunnel run cli test
  tags:
    - docker

# Stage: update internal images

.update_internal_image: &update_internal_image
  stage: update internal images
  only:
    - /^master$/
  tags:
    - docker

update development image:
  <<: *update_internal_image
  script: rit tunnel run cli update development

update test image:
  <<: *update_internal_image
  script: rit tunnel run cli update test

update release image:
  <<: *update_internal_image
  script: rit tunnel run cli update release
