image: ritproject/cli:docker
services:
  - docker:dind
stages:
  - test
  - update images

# Stage: test

test:
  stage: test
  before_script:
    - rit config tunnel add repo https://gitlab.com/ritproject/workspace
    - rit config tunnel default set workspace
  script: rit tunnel run cli test
  tags:
    - docker

# Stage: update images

.update_image: &update_image
  stage: update images
  before_script:
    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - rit config tunnel add repo https://gitlab.com/ritproject/workspace
    - rit config tunnel default set workspace
  only:
    - /^master$/
  tags:
    - docker

update development image:
  <<: *update_image
  script: rit tunnel run cli update development

update test image:
  <<: *update_image
  script: rit tunnel run cli update test

update docker image:
  <<: *update_image
  script: rit tunnel run cli update docker

update production image:
  <<: *update_image
  script: rit tunnel run cli update production
